#!/usr/bin/env python3
"""Read all bench/results/*.json and emit a comparison report.

Outputs:
  bench/REPORT.md           — side-by-side Markdown tables
  bench/plots/*.png         — optional matplotlib plots (skipped if mpl
                              is unavailable)

The bench harness already aggregates per-(topology, workload, concurrency)
tuples; here we just transpose them into the topology-vs-topology view.
"""
from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = ROOT / "bench" / "results"
REPORT_PATH = ROOT / "bench" / "REPORT.md"
PLOTS_DIR = ROOT / "bench" / "plots"


def load_results(path: Path) -> List[dict]:
    out = []
    for f in sorted(path.glob("*.json")):
        if f.name.startswith("_"):
            continue
        try:
            out.append(json.loads(f.read_text()))
        except Exception as e:
            print(f"  skipping {f}: {e}")
    return out


def jain_avg(values: List[float]) -> float:
    return round(statistics.mean(values), 4) if values else 0.0


def render_markdown(results: List[dict]) -> str:
    lines: List[str] = []
    lines.append("# Mini 2 — topology comparison\n")
    lines.append(f"_{len(results)} topologies, generated by `bench/topo_compare.py`_\n")

    workloads = []
    concurrencies = []
    for r in results:
        for w in r.get("workloads", []):
            if w["workload"] not in workloads:
                workloads.append(w["workload"])
            if w["concurrency"] not in concurrencies:
                concurrencies.append(w["concurrency"])
    workloads.sort(key=lambda x: ["narrow", "small", "medium", "broad"].index(x)
                   if x in ["narrow", "small", "medium", "broad"] else 99)
    concurrencies.sort()

    # ------------------------------------------------------------------
    # Headline: latency p95 at concurrency=1, "small" workload.
    # ------------------------------------------------------------------
    lines.append("\n## Headline: query latency at concurrency=1, small selectivity (~3%)\n")
    lines.append("| topology | rows | mean ms | p95 ms | first chunk ms |")
    lines.append("|---|---:|---:|---:|---:|")
    for r in results:
        topo = r["topology"]
        if r.get("error"):
            lines.append(f"| {topo} | — | — | — | ERROR: {r['error']} |")
            continue
        cell = next((w for w in r["workloads"] if w["workload"] == "small" and w["concurrency"] == 1), None)
        if not cell:
            lines.append(f"| {topo} | — | — | — | (no data) |")
            continue
        lines.append(f"| {topo} | {cell['rows_mean']} | {cell['ms']['mean']} | {cell['ms']['p95']} | {cell['first_chunk_ms']['mean']} |")

    # ------------------------------------------------------------------
    # Full sweep: per-(workload, concurrency) latency p95 across topologies.
    # ------------------------------------------------------------------
    for w_name in workloads:
        lines.append(f"\n## Workload `{w_name}` — p95 ms across topologies\n")
        header = "| topology |" + "".join(f" c={c} |" for c in concurrencies)
        sep    = "|---|" + "".join("---:|" for _ in concurrencies)
        lines.append(header)
        lines.append(sep)
        for r in results:
            if r.get("error"):
                continue
            row = [r["topology"]]
            for c in concurrencies:
                cell = next((x for x in r["workloads"]
                             if x["workload"] == w_name and x["concurrency"] == c), None)
                row.append(f"{cell['ms']['p95']}" if cell else "—")
            lines.append("| " + " | ".join(row) + " |")

    # Fairness summary.
    lines.append("\n## Fairness — Jain's index averaged across workloads, by concurrency\n")
    lines.append("| topology |" + "".join(f" c={c} |" for c in concurrencies))
    lines.append("|---|" + "".join("---:|" for _ in concurrencies))
    for r in results:
        if r.get("error"):
            continue
        row = [r["topology"]]
        for c in concurrencies:
            xs = [w["jains_index"] for w in r["workloads"]
                  if w["concurrency"] == c and w.get("jains_index") is not None]
            row.append(f"{jain_avg(xs):.4f}" if xs else "—")
        lines.append("| " + " | ".join(row) + " |")

    # Winner per metric (concurrency=1 mean ms, by workload).
    lines.append("\n## Winners (lowest mean latency at concurrency=1)\n")
    lines.append("| workload | winner | mean ms | runner-up | gap |")
    lines.append("|---|---|---:|---|---:|")
    for w_name in workloads:
        ranked = []
        for r in results:
            if r.get("error"):
                continue
            cell = next((x for x in r["workloads"]
                         if x["workload"] == w_name and x["concurrency"] == 1), None)
            if cell:
                ranked.append((cell["ms"]["mean"], r["topology"]))
        if not ranked:
            continue
        ranked.sort()
        winner = ranked[0]
        runner = ranked[1] if len(ranked) > 1 else (winner[0], "-")
        gap = round(runner[0] - winner[0], 1) if len(ranked) > 1 else 0
        lines.append(f"| {w_name} | **{winner[1]}** | {winner[0]} | {runner[1]} | +{gap} |")

    return "\n".join(lines) + "\n"


def render_plots(results: List[dict]) -> List[Path]:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("[compare] matplotlib not installed — skipping plots")
        return []

    PLOTS_DIR.mkdir(parents=True, exist_ok=True)
    written = []

    # 1) Mean latency vs concurrency, lines per topology, "small" workload.
    fig, ax = plt.subplots(figsize=(8, 5))
    for r in results:
        if r.get("error"): continue
        cs, ms = [], []
        for w in r["workloads"]:
            if w["workload"] == "small":
                cs.append(w["concurrency"]); ms.append(w["ms"]["mean"])
        if cs:
            ax.plot(cs, ms, marker="o", label=r["topology"])
    ax.set_xlabel("concurrency")
    ax.set_ylabel("mean ms")
    ax.set_title("Mean latency vs concurrency (small workload)")
    ax.legend(loc="best", fontsize=8); ax.grid(True, alpha=0.3)
    p = PLOTS_DIR / "latency_vs_concurrency_small.png"
    fig.tight_layout(); fig.savefig(p, dpi=120); plt.close(fig); written.append(p)

    # 2) p95 latency by topology, bar chart, concurrency=1, small.
    fig, ax = plt.subplots(figsize=(8, 5))
    rows = []
    for r in results:
        if r.get("error"): continue
        cell = next((x for x in r["workloads"] if x["workload"] == "small" and x["concurrency"] == 1), None)
        if cell: rows.append((r["topology"], cell["ms"]["p95"]))
    rows.sort(key=lambda x: x[1])
    if rows:
        names = [x[0] for x in rows]; vals = [x[1] for x in rows]
        ax.barh(names, vals)
        ax.set_xlabel("p95 ms")
        ax.set_title("p95 latency by topology (concurrency=1, small)")
        for i, v in enumerate(vals):
            ax.text(v, i, f" {v:.0f}", va="center", fontsize=8)
        p = PLOTS_DIR / "p95_by_topology_small_c1.png"
        fig.tight_layout(); fig.savefig(p, dpi=120); plt.close(fig); written.append(p)

    return written


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", type=Path, default=RESULTS_DIR)
    ap.add_argument("--out", type=Path, default=REPORT_PATH)
    ap.add_argument("--no-plots", action="store_true")
    args = ap.parse_args()

    results = load_results(args.results)
    if not results:
        print(f"no results in {args.results}; run topo_bench.py first")
        return 1

    md = render_markdown(results)
    args.out.write_text(md)
    print(f"wrote {args.out}")
    if not args.no_plots:
        for p in render_plots(results):
            print(f"wrote {p}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
