# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mini2_pb2 as mini2__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mini2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientGatewayStub(object):
    """Client-facing external API (only A implements this for external clients).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitQuery = channel.unary_unary(
                '/mini2.ClientGateway/SubmitQuery',
                request_serializer=mini2__pb2.Query.SerializeToString,
                response_deserializer=mini2__pb2.QueryAck.FromString,
                _registered_method=True)
        self.FetchChunk = channel.unary_unary(
                '/mini2.ClientGateway/FetchChunk',
                request_serializer=mini2__pb2.PullRequest.SerializeToString,
                response_deserializer=mini2__pb2.Chunk.FromString,
                _registered_method=True)
        self.CancelQuery = channel.unary_unary(
                '/mini2.ClientGateway/CancelQuery',
                request_serializer=mini2__pb2.CancelRequest.SerializeToString,
                response_deserializer=mini2__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/mini2.ClientGateway/Ping',
                request_serializer=mini2__pb2.Heartbeat.SerializeToString,
                response_deserializer=mini2__pb2.HeartbeatAck.FromString,
                _registered_method=True)


class ClientGatewayServicer(object):
    """Client-facing external API (only A implements this for external clients).
    """

    def SubmitQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitQuery,
                    request_deserializer=mini2__pb2.Query.FromString,
                    response_serializer=mini2__pb2.QueryAck.SerializeToString,
            ),
            'FetchChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchChunk,
                    request_deserializer=mini2__pb2.PullRequest.FromString,
                    response_serializer=mini2__pb2.Chunk.SerializeToString,
            ),
            'CancelQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelQuery,
                    request_deserializer=mini2__pb2.CancelRequest.FromString,
                    response_serializer=mini2__pb2.CancelResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=mini2__pb2.Heartbeat.FromString,
                    response_serializer=mini2__pb2.HeartbeatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mini2.ClientGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mini2.ClientGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientGateway(object):
    """Client-facing external API (only A implements this for external clients).
    """

    @staticmethod
    def SubmitQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.ClientGateway/SubmitQuery',
            mini2__pb2.Query.SerializeToString,
            mini2__pb2.QueryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.ClientGateway/FetchChunk',
            mini2__pb2.PullRequest.SerializeToString,
            mini2__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.ClientGateway/CancelQuery',
            mini2__pb2.CancelRequest.SerializeToString,
            mini2__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.ClientGateway/Ping',
            mini2__pb2.Heartbeat.SerializeToString,
            mini2__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PeerLinkStub(object):
    """Node-to-node API. Every process (A–I) implements this.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ForwardQuery = channel.unary_unary(
                '/mini2.PeerLink/ForwardQuery',
                request_serializer=mini2__pb2.ForwardedQuery.SerializeToString,
                response_deserializer=mini2__pb2.QueryAck.FromString,
                _registered_method=True)
        self.PullChunk = channel.unary_unary(
                '/mini2.PeerLink/PullChunk',
                request_serializer=mini2__pb2.PullRequest.SerializeToString,
                response_deserializer=mini2__pb2.Chunk.FromString,
                _registered_method=True)
        self.PushChunk = channel.unary_unary(
                '/mini2.PeerLink/PushChunk',
                request_serializer=mini2__pb2.Chunk.SerializeToString,
                response_deserializer=mini2__pb2.PushChunkAck.FromString,
                _registered_method=True)
        self.CancelQuery = channel.unary_unary(
                '/mini2.PeerLink/CancelQuery',
                request_serializer=mini2__pb2.CancelRequest.SerializeToString,
                response_deserializer=mini2__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/mini2.PeerLink/Ping',
                request_serializer=mini2__pb2.Heartbeat.SerializeToString,
                response_deserializer=mini2__pb2.HeartbeatAck.FromString,
                _registered_method=True)


class PeerLinkServicer(object):
    """Node-to-node API. Every process (A–I) implements this.
    """

    def ForwardQuery(self, request, context):
        """Peer A asks peer B to start answering a query. B returns an ack with
        estimated row count; B then locally enqueues rows for later PullChunk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullChunk(self, request, context):
        """Peer A pulls chunks from peer B for a request previously forwarded.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushChunk(self, request, context):
        """Parent forwards a push (not used in the pure pull model, but present
        so we can experiment with mixed models).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerLinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ForwardQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardQuery,
                    request_deserializer=mini2__pb2.ForwardedQuery.FromString,
                    response_serializer=mini2__pb2.QueryAck.SerializeToString,
            ),
            'PullChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.PullChunk,
                    request_deserializer=mini2__pb2.PullRequest.FromString,
                    response_serializer=mini2__pb2.Chunk.SerializeToString,
            ),
            'PushChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.PushChunk,
                    request_deserializer=mini2__pb2.Chunk.FromString,
                    response_serializer=mini2__pb2.PushChunkAck.SerializeToString,
            ),
            'CancelQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelQuery,
                    request_deserializer=mini2__pb2.CancelRequest.FromString,
                    response_serializer=mini2__pb2.CancelResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=mini2__pb2.Heartbeat.FromString,
                    response_serializer=mini2__pb2.HeartbeatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mini2.PeerLink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mini2.PeerLink', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerLink(object):
    """Node-to-node API. Every process (A–I) implements this.
    """

    @staticmethod
    def ForwardQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.PeerLink/ForwardQuery',
            mini2__pb2.ForwardedQuery.SerializeToString,
            mini2__pb2.QueryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.PeerLink/PullChunk',
            mini2__pb2.PullRequest.SerializeToString,
            mini2__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.PeerLink/PushChunk',
            mini2__pb2.Chunk.SerializeToString,
            mini2__pb2.PushChunkAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.PeerLink/CancelQuery',
            mini2__pb2.CancelRequest.SerializeToString,
            mini2__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.PeerLink/Ping',
            mini2__pb2.Heartbeat.SerializeToString,
            mini2__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
